from locustfiles.search_httplocust import SearchUser
# from locustfiles.upload_dsslocust import UploadUser
from locustfiles.download_dsslocust import DownloadUser
from locustfiles.checkout_dsslocust import CheckoutUser
from locustfiles.notify_dsslocust import NotifiedUser