from locustfiles.checkout_dsslocust import CheckoutUser, CheckoutTaskSet, CheckoutFixedTaskSet
from locustfiles.download_dsslocust import DownloadUser, DownloadTaskSet, DownloadFixedTaskSet
from locustfiles.search_httplocust import SearchUser, SearchTaskSet
from locustfiles.upload_dsslocust import UploadUser, UploadLocalTaskSet, UploadCloudTaskSet
from locustfiles.notify_dsslocust import NotifyTaskSet
from locustfiles.common.dsslocust import DSSLocust
